### ISSUE TITLE
Release version v0.11

### ISSUE THREAD

**Issue by ctdean** [lvh/caesium#33]
We've started to use caesium (which is great) and wanted to use some of the pwhash functions. What's the ETA on the next release?

Thanks!

**Comment by lvh** [comment]
I hope to take a look tonight to see what needs to change before I can comfortably cut a release. I'm on a newish laptop here but I'm not expecting any difficulties with Clojars or anything.

**Comment by lvh** [comment]
(Also, if you don't mind disclosing, I'd love to know who's using caesium and what for :))

**Comment by lvh** [comment]
I can't get the tests to pass on this machine. Do the tests run in a checkout for you, and with which version of libsodium?

**Comment by lvh** [comment]
Ugh. Looks like libsodium changed the default hashing algorithm between 1.0.14 and 1.0.15.

**Comment by lvh** [comment]
There are a few other issues here that need to be resolved:

- documentation for pwhash 
- support for 1.0.14 and 1.0.15 (#34) 
- pwhash operations can fail, but currently this code doesn't raise when it does. For example, when you run these tests on 1.0.14, you just get an all-zero buffer back:

```
FAIL in (pwhash-argon2id-alg-argon2id13-test) (pwhash_test.clj:143)

expected: "86b902e6577791ff5e1aaa73a57d21ee7a8822ed8e183940af4fa1ba6ab9803c"
  actual: "0000000000000000000000000000000000000000000000000000000000000000"

    diff: - "86b902e6577791ff5e1aaa73a57d21ee7a8822ed8e183940af4fa1ba6ab9803c"
          + "0000000000000000000000000000000000000000000000000000000000000000"
```

This appears to be because in between 1.0.15 and 1.0.14, libsodium increased the mandatory minimum operations limit (`OPSLIMIT_MIN`) for argon2id changed from 1 to 3.

At least we're in good company: https://github.com/joshjdevl/libsodium-jni/issues/93

**Comment by lvh** [comment]
(For context, if you look at the PR: I didn't write the pwhash functionality and haven't thoroughly tested it, which is why I haven't cut a release yet. Looks like that wasn't a bad call :))

**Comment by ctdean** [comment]
Thanks for all the work.

We're using caesium in our startup in SF. We've wanted to use sodium for a while, but our last gig was inside a US Bank and for complicated reasons we could get the library installed there.

**Comment by ctdean** [comment]
Version wise, we're still running 1.0.13, but I assumed we would upgrade soon.

**Comment by lvh** [comment]
Closing because there are other tickets covering what needs to get done, and this has been open for a while :)
