### ISSUE TITLE
Inscrutable errors when libsodium is not installed

### ISSUE THREAD

**Issue by arohner** [lvh/caesium#55]
I attempted to use caesium when libsodium was not yet installed. I ran `(require 'caesium.crypto.pwhash)` and got an error "code size limit exceeded". An error like "libsodium is not installed" would have saved me a whole lot of searching and debugging.

**Comment by TomLisankie** [comment]
I agree, this would have been very helpful especially since I was sitting trying to figure out what the code size could possibly have to do with now being able to require this library. Then I remembered Caesium is dependent on libsodium being installed (which I didn't have installed) and saw your issue. Installed libsodium and now everything works fine.

**Comment by dspearson** [comment]
I believe this issue can now be closed.

**Comment by lvh** [comment]
Indeed it can. Thanks @dspearson !
